### PR TITLE
fix: remove unnecessary data

### PR DESCRIPTION
**Pull request by emersongcardona**

### CODE REVIEW

**Review by ldonis — CHANGES_REQUESTED** [review]
No pasa ningun test

Screen Shot 2022-06-03 at 09 40 48

**Comment by FR98** [comment]
@emersongcardona is working on fixing all the tests

**Comment by emersongcardona** [comment]
a new PR is open with test for the 3 types of topics: config,event,data

**Comment by FR98** [comment]
Ya pasan los tests 👍🏽

**Review by FR98 — APPROVED** [review]

**Comment by FR98** [comment]
ya pasan los tests, se arreglaron en otro PR que ya esta en master

**Review by ldonis — APPROVED** [review]

**Pull request merged**
